version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ManhND*2000
      MYSQL_DATABASE: manhnd5
      MYSQL_USER: manhnd5
      MYSQL_PASSWORD: pvcb@1234
