//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEdmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SendMailEntities : DbContext
    {
        public SendMailEntities()
            : base("name=SendMailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<MessageBody> MessageBodies { get; set; }
        public virtual DbSet<MessageBodyDay> MessageBodyDays { get; set; }
        public virtual DbSet<MessageBodyNight> MessageBodyNights { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<ToEmail> ToEmails { get; set; }
    }
}
