filebeat.inputs:
# Tại đây cấu hình các nơi để thu thập log (chú ý nếu là đường dẫn vật lý trên máy thì phải mout vào trong cotainer ở file docker-compose.yml)
- type: log
  paths:
    - /var/log/logback/*.log
  enabled: true

output.logstash:
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "JzpWCIbjYJKzHHzxJGkW"

