spring:
#  jpa
  datasource:
    url: jdbc:mysql://localhost:3307/manhnd5
    username: root
    password: ManhND*2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  Cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: Manh*2000
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
