version: '3.8'

services:
  auto-send-mail:
    image: auto-send-mail
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json
